---
abstract: 'Rebuild HTTP sessions from pcap streams'
author:
  - 'David Cannings <david@edeca.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.93'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Sessioniser
no_index:
  directory:
    - inc
    - t
requires:
  HTTP::Parser: 0
  IO::Compress::Gzip: 0
  Net::LibNIDS: 0.02
  perl: 5.8.8
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/edeca/HTTP-Sessioniser
version: 0.05
